---
version: "3.2"

services:
    oragono:
        image: oragono/oragono:latest
        ports:
            - "6667:6667/tcp"
            - "6697:6697/tcp"
        volumes:
            - /dockervols/ircd:/ircd
            - /dockervols/nginx-letsencrypt/etc/letsencrypt/live/klar.sh/fullchain.pem:/ircd/fullchain.pem:ro
            - /dockervols/nginx-letsencrypt/etc/letsencrypt/live/klar.sh/privkey.pem:/ircd/privkey.pem:ro
        restart: unless-stopped
        network_mode: "host"
